system:
  upload: D:\blogUpdata
spring:
  profiles:
    active:
  datasource:
      url: jdbc:mysql://120.79.62.203:3306/blogWeb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Zh@19970322
      driver-class-name: com.mysql.cj.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 120.79.62.203
    port: 6379
    password: zhanghang

  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  http:
    encoding:
      charset: utf-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  file: /tmp
server:
  servlet:
    context-path: /blog
  port: 8088
  tomcat:
    uri-encoding: utf-8
#  # security 使能
#security:
#  basic:
#    enabled: false

