spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/dc?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Zh@19970322
      driver-class-name: com.mysql.cj.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.2.23
    port: 6379
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  http:
    encoding:
      charset: utf-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  file: /home/leanin
server:
  servlet:
    context-path: /dc
  port: 8088

#  # security 使能
#security:
#  basic:
#    enabled: false

